# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gsd/.rev/.tools/binja_plugins/snap_viewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gsd/.rev/.tools/binja_plugins/snap_viewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gsd/.rev/.tools/binja_plugins/snap_viewer/CMakeFiles /home/gsd/.rev/.tools/binja_plugins/snap_viewer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gsd/.rev/.tools/binja_plugins/snap_viewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/gsd/.rev/.tools/binja_plugins/snap_viewer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named snapviewer

# Build rule for target.
snapviewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snapviewer
.PHONY : snapviewer

# fast build rule for target.
snapviewer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/build
.PHONY : snapviewer/fast

#=============================================================================
# Target rules for targets named snapviewer_autogen_timestamp_deps

# Build rule for target.
snapviewer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snapviewer_autogen_timestamp_deps
.PHONY : snapviewer_autogen_timestamp_deps

# fast build rule for target.
snapviewer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer_autogen_timestamp_deps.dir/build.make CMakeFiles/snapviewer_autogen_timestamp_deps.dir/build
.PHONY : snapviewer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named snapviewer_autogen

# Build rule for target.
snapviewer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snapviewer_autogen
.PHONY : snapviewer_autogen

# fast build rule for target.
snapviewer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer_autogen.dir/build.make CMakeFiles/snapviewer_autogen.dir/build
.PHONY : snapviewer_autogen/fast

#=============================================================================
# Target rules for targets named binaryninjaapi

# Build rule for target.
binaryninjaapi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binaryninjaapi
.PHONY : binaryninjaapi

# fast build rule for target.
binaryninjaapi/fast:
	$(MAKE) $(MAKESILENT) -f build/CMakeFiles/binaryninjaapi.dir/build.make build/CMakeFiles/binaryninjaapi.dir/build
.PHONY : binaryninjaapi/fast

Plugin.o: Plugin.cpp.o
.PHONY : Plugin.o

# target to build an object file
Plugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/Plugin.cpp.o
.PHONY : Plugin.cpp.o

Plugin.i: Plugin.cpp.i
.PHONY : Plugin.i

# target to preprocess a source file
Plugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/Plugin.cpp.i
.PHONY : Plugin.cpp.i

Plugin.s: Plugin.cpp.s
.PHONY : Plugin.s

# target to generate assembly for a file
Plugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/Plugin.cpp.s
.PHONY : Plugin.cpp.s

UI/snap_viewer.o: UI/snap_viewer.cpp.o
.PHONY : UI/snap_viewer.o

# target to build an object file
UI/snap_viewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/UI/snap_viewer.cpp.o
.PHONY : UI/snap_viewer.cpp.o

UI/snap_viewer.i: UI/snap_viewer.cpp.i
.PHONY : UI/snap_viewer.i

# target to preprocess a source file
UI/snap_viewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/UI/snap_viewer.cpp.i
.PHONY : UI/snap_viewer.cpp.i

UI/snap_viewer.s: UI/snap_viewer.cpp.s
.PHONY : UI/snap_viewer.s

# target to generate assembly for a file
UI/snap_viewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/UI/snap_viewer.cpp.s
.PHONY : UI/snap_viewer.cpp.s

snapviewer_autogen/mocs_compilation.o: snapviewer_autogen/mocs_compilation.cpp.o
.PHONY : snapviewer_autogen/mocs_compilation.o

# target to build an object file
snapviewer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/snapviewer_autogen/mocs_compilation.cpp.o
.PHONY : snapviewer_autogen/mocs_compilation.cpp.o

snapviewer_autogen/mocs_compilation.i: snapviewer_autogen/mocs_compilation.cpp.i
.PHONY : snapviewer_autogen/mocs_compilation.i

# target to preprocess a source file
snapviewer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/snapviewer_autogen/mocs_compilation.cpp.i
.PHONY : snapviewer_autogen/mocs_compilation.cpp.i

snapviewer_autogen/mocs_compilation.s: snapviewer_autogen/mocs_compilation.cpp.s
.PHONY : snapviewer_autogen/mocs_compilation.s

# target to generate assembly for a file
snapviewer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snapviewer.dir/build.make CMakeFiles/snapviewer.dir/snapviewer_autogen/mocs_compilation.cpp.s
.PHONY : snapviewer_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... snapviewer_autogen"
	@echo "... snapviewer_autogen_timestamp_deps"
	@echo "... binaryninjaapi"
	@echo "... snapviewer"
	@echo "... Plugin.o"
	@echo "... Plugin.i"
	@echo "... Plugin.s"
	@echo "... UI/snap_viewer.o"
	@echo "... UI/snap_viewer.i"
	@echo "... UI/snap_viewer.s"
	@echo "... snapviewer_autogen/mocs_compilation.o"
	@echo "... snapviewer_autogen/mocs_compilation.i"
	@echo "... snapviewer_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/gsd/.rev/.tools/binja_plugins/snap_viewer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

